### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [calba5141114/bewContractorProject#1]
Nice work, @calba5141114 --- a few things are still required in order to pass this project:

- Must CRUD >= 2 resources and associate them: right now, your project doesn't utilize an association.
- Missing 100% test coverage.
- Missing Heroku link: please add to `README`. 

Please make the corrections by EOD and I'll circle back to check it out.
Thanks!
-d

**Comment by chalkedgoose** [comment]
my bad i need to put the heroku link on it

**Comment by droxey** [comment]
Nice job!! just in time --- this is now a passing project!
